#!/usr/bin/env python3
"""Summarize manual Windows release gates and latest evidence packets."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path


GATES = (
    (
        "Clean Windows VM",
        "CLEAN_VM_VERIFICATION.md",
        "build/windows/manual-evidence/clean-vm",
    ),
    (
        "OBS Virtual Camera",
        "OBS_VIRTUAL_CAMERA_VERIFICATION.md",
        "build/windows/manual-evidence/obs-virtualcam",
    ),
    (
        "Legal Review",
        "LEGAL_REVIEW.md",
        "build/windows/manual-evidence/legal-review",
    ),
)


@dataclass(frozen=True)
class GateSummary:
    name: str
    path: str
    status: str
    open_items: list[str]
    latest_evidence: str

    @property
    def passed(self) -> bool:
        return self.status == "PASS" and not self.open_items

    def to_dict(self) -> dict[str, object]:
        return {
            "name": self.name,
            "path": self.path,
            "status": self.status,
            "open_items": self.open_items,
            "open_item_count": len(self.open_items),
            "latest_evidence": self.latest_evidence,
            "passed": self.passed,
        }


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def gate_status(text: str, exists: bool) -> str:
    if not exists:
        return "MISSING"
    match = re.search(r"^Status:\s*(\S+)", text, flags=re.MULTILINE | re.IGNORECASE)
    return match.group(1).upper() if match else "UNKNOWN"


def open_checklist_items(text: str) -> list[str]:
    items: list[str] = []
    for line in text.splitlines():
        if re.match(r"^\s*-\s*\[\s\]", line):
            items.append(re.sub(r"^\s*-\s*\[\s\]\s*", "", line).strip())
    return items


def latest_evidence(repo_root: Path, evidence_dir: str) -> str:
    directory = repo_root / evidence_dir
    if not directory.exists():
        return ""
    candidates = [path for path in directory.glob("*.md") if path.is_file()]
    if not candidates:
        return ""
    latest = max(candidates, key=lambda path: (path.stat().st_mtime, path.name))
    return latest.relative_to(repo_root).as_posix()


def collect(repo_root: Path) -> list[GateSummary]:
    summaries: list[GateSummary] = []
    for name, gate_path, evidence_dir in GATES:
        path = repo_root / gate_path
        text = read_text(path)
        summaries.append(
            GateSummary(
                name=name,
                path=gate_path,
                status=gate_status(text, path.exists()),
                open_items=open_checklist_items(text),
                latest_evidence=latest_evidence(repo_root, evidence_dir),
            )
        )
    return summaries


def render_markdown(summaries: list[GateSummary]) -> str:
    lines = [
        "# Manual Windows Release Gate Summary",
        "",
        "This report is generated by `tools/summarize_manual_release_gates.py`.",
        "It does not approve the release; it shows which human gates still need",
        "completion before publishing.",
        "",
        "## Status",
        "",
    ]
    for summary in summaries:
        marker = "PASS" if summary.passed else "BLOCKED"
        evidence = summary.latest_evidence or "none found"
        lines.append(f"- {marker}: `{summary.path}` status=`{summary.status}` open_items=`{len(summary.open_items)}` latest_evidence=`{evidence}`")

    lines.extend(["", "## Open Items", ""])
    any_open = False
    for summary in summaries:
        if summary.open_items:
            any_open = True
            lines.append(f"### {summary.name}")
            lines.append("")
            for item in summary.open_items:
                lines.append(f"- {item}")
            lines.append("")
    if not any_open:
        lines.append("- None.")
        lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Summarize manual Windows release gates.")
    parser.add_argument("--repo-root", default=".", help="Repository root.")
    parser.add_argument("--output", help="Write markdown summary to this path.")
    parser.add_argument("--json-output", help="Write JSON summary to this path.")
    parser.add_argument("--strict", action="store_true", help="Exit non-zero unless every gate is PASS with no open checklist items.")
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    summaries = collect(repo_root)
    markdown = render_markdown(summaries)
    print(markdown)

    if args.output:
        output = (repo_root / args.output).resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(markdown, encoding="utf-8")

    if args.json_output:
        payload = {
            "ready": all(summary.passed for summary in summaries),
            "gates": [summary.to_dict() for summary in summaries],
        }
        json_output = (repo_root / args.json_output).resolve()
        json_output.parent.mkdir(parents=True, exist_ok=True)
        json_output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    if args.strict and not all(summary.passed for summary in summaries):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
